import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import Menu from '@/components/Menu';

const inter = Inter({
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Spotify Search App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/css/materialdesignicons.min.css"
                />
            </head>
            <body
                className={`${inter.className} antialiased`}
            >
                <Menu />
                {children}
            </body>
        </html>
    );
}
